version: "2.3"

services:
  terra: &terra
    build: &terra_build
      context: .
      dockerfile: docker/terra.Dockerfile
    # prevent different users from clobbering each others images
    image: ${TERRA_DOCKER_REPO}:terra_${TERRA_USERNAME}
    environment:
      # Variables for docker_entrypoint.bsh
      - DOCKER_UID=${TERRA_UID}
      - DOCKER_GIDS=${TERRA_GIDS}
      - DOCKER_GROUP_NAMES=${TERRA_GROUP_NAMES}
      - DOCKER_USERNAME=user
      - DISPLAY
      - PYTHONPATH=${TERRA_SOURCE_DIR_DOCKER}:${TERRA_INSTALL_DIR_DOCKER}/lib/python3/site-packages
    cap_add:
      - SYS_PTRACE # Useful for gdb
    volumes:
      - &terra_source_volume
        type: ${TERRA_SOURCE_DIR_TYPE}
        source: ${TERRA_SOURCE_DIR}
        target: ${TERRA_SOURCE_DIR_DOCKER}
        read_only: true
      - &terra_install_volume
        type: ${TERRA_INSTALL_DIR_TYPE}
        source: ${TERRA_INSTALL_DIR}
        target: ${TERRA_INSTALL_DIR_DOCKER}
      - type: volume
        source: venv
        target: /venv
  compile:
    <<: *terra
    build:
      <<: *terra_build
      target: compile
    image: ${TERRA_DOCKER_REPO}:terra_compile_${TERRA_USERNAME}
    volumes:
      - *terra_source_volume
      - *terra_install_volume
      - type: ${TERRA_BUILD_DIR_TYPE}
        source: ${TERRA_BUILD_DIR}
        target: ${TERRA_BUILD_DIR_DOCKER}

volumes:
  venv:
    labels:
      com.vsi.just.clean_action: ask
  terra-install:
  terra-build:
