version: "2.3"

services:
  terra: &terra
    build: &terra_build
      context: .
      dockerfile: docker/terra.Dockerfile
    # prevent different users from clobbering each others images
    image: ${TERRA_DOCKER_REPO}:terra_${TERRA_USERNAME}
    environment:
      # Variables for docker_entrypoint.bsh
      - DOCKER_UID=${TERRA_UID}
      - DOCKER_GIDS=${TERRA_GIDS}
      - DOCKER_GROUP_NAMES=${TERRA_GROUP_NAMES}
      - DOCKER_USERNAME=user
      - DISPLAY
      - PYTHONPATH=${TERRA_SOURCE_DIR_DOCKER}:${TERRA_INSTALL_DIR_DOCKER}/lib/python3/site-packages:${TERRA_SOURCE_DIR_DOCKER}/external/vsi_common/python
    cap_add:
      - SYS_PTRACE # Useful for gdb
    volumes:
      - &terra_source_volume
        type: ${TERRA_SOURCE_DIR_TYPE}
        source: ${TERRA_SOURCE_DIR}
        target: ${TERRA_SOURCE_DIR_DOCKER}
        read_only: true
      - &terra_vsi_volume
        type: ${TERRA_SOURCE_DIR_TYPE}
        source: ${TERRA_SOURCE_DIR}/external/vsi_common
        target: /vsi
        read_only: true
      - &terra_install_volume
        type: ${TERRA_INSTALL_DIR_TYPE}
        source: ${TERRA_INSTALL_DIR}
        target: ${TERRA_INSTALL_DIR_DOCKER}
      - &terra_venv_volume
        type: volume
        source: venv
        target: /venv
  compile:
    <<: *terra
    build:
      <<: *terra_build
      target: compile
    image: ${TERRA_DOCKER_REPO}:terra_compile_${TERRA_USERNAME}
    volumes:
      - *terra_source_volume
      - *terra_install_volume
      - *terra_vsi_volume
      - type: ${TERRA_BUILD_DIR_TYPE}
        source: ${TERRA_BUILD_DIR}
        target: ${TERRA_BUILD_DIR_DOCKER}

  test:
    <<: *terra
    volumes:
      - <<: *terra_source_volume
        read_only: false
      - *terra_install_volume
      - *terra_venv_volume
      - *terra_vsi_volume

  ipykernel:
    <<: *terra
    ports:
      - "${JUPYTER_CONTROL_PORT_HOST-10001}:${JUPYTER_CONTROL_PORT-10001}"
      - "${JUPYTER_HB_PORT_HOST-10002}:${JUPYTER_HB_PORT-10002}"
      - "${JUPYTER_IOPUB_PORT_HOST-10003}:${JUPYTER_IOPUB_PORT-10003}"
      - "${JUPYTER_SHELL_PORT_HOST-10004}:${JUPYTER_SHELL_PORT-10004}"
      - "${JUPYTER_STDIN_PORT_HOST-10005}:${JUPYTER_STDIN_PORT-10005}"
    # command: bash -c "declare -i x=1000; while (( x )); do if pgrep python; then x=1000; else x=x-15; fi; declare -p x; sleep 15; done"

  ipython-kernel:
    <<: *terra
    network_mode: host

volumes:
  venv:
    labels:
      com.vsi.just.clean_action: delete
      com.vsi.just.clean_setup: run terra nopipenv true
  terra-install:
  terra-build:
