version: "3.7"

services:
  terra: &terra
    build: &terra_build
      context: .
      dockerfile: docker/terra.Dockerfile
    # prevent different users from clobbering each others images
    image: ${TERRA_DOCKER_REPO}:terra_${TERRA_USERNAME}
    environment:
      # Variables for docker_entrypoint.bsh
      - DOCKER_UID=${TERRA_UID}
      - DOCKER_GIDS=${TERRA_GIDS}
      - DOCKER_GROUP_NAMES=${TERRA_GROUP_NAMES}
      - DOCKER_USERNAME=user
      - DISPLAY
      - JUSTFILE=${TERRA_TERRA_DIR_DOCKER}/docker/terra.Justfile
      - JUST_SETTINGS=${TERRA_TERRA_DIR_DOCKER}/terra.env
    cap_add:
      - SYS_PTRACE # Useful for gdb
    volumes:
      # source code
      - &terra_source_volume
        type: ${TERRA_TERRA_DIR_TYPE}
        source: ${TERRA_TERRA_DIR}
        target: ${TERRA_TERRA_DIR_DOCKER}
        read_only: true
      # vsi_common
      - &terra_vsi_volume
        type: ${TERRA_TERRA_DIR_TYPE}
        source: ${TERRA_TERRA_DIR}/external/vsi_common
        target: /vsi
        read_only: true
      # The storage location of the pipenv virtualenv and venv cache
      - &terra_venv_volume
        type: volume
        source: venv
        target: /venv
      # The settings volume is used for settings files around
      # - &terra_settings
      #   type: bind
      #   source: ${TERRA_SETTINGS_DIR-}
      #   target: ${TERRA_SETTINGS_DIR_DOCKER}

  test:
    <<: *terra
    volumes:
      - <<: *terra_source_volume
        read_only: false
      - *terra_venv_volume
      - *terra_vsi_volume

  ipykernel:
    <<: *terra
    ports:
      - "${JUPYTER_CONTROL_PORT_HOST-10001}:${JUPYTER_CONTROL_PORT-10001}"
      - "${JUPYTER_HB_PORT_HOST-10002}:${JUPYTER_HB_PORT-10002}"
      - "${JUPYTER_IOPUB_PORT_HOST-10003}:${JUPYTER_IOPUB_PORT-10003}"
      - "${JUPYTER_SHELL_PORT_HOST-10004}:${JUPYTER_SHELL_PORT-10004}"
      - "${JUPYTER_STDIN_PORT_HOST-10005}:${JUPYTER_STDIN_PORT-10005}"

volumes:
  venv:
    labels:
      com.vsi.just.clean_action: delete
      com.vsi.just.clean_setup: run terra nopipenv true
