version: "2.3"

services:
  vxl: &vxl_anchor
    build:
      context: .
      dockerfile: docker/vxl.Dockerfile
    # prevent different users from clobbering each others images
    image: ${VXL_DOCKER_REPO}:vxl_${VXL_USERNAME}
    environment:
      # Variables for docker_entrypoint.bsh
      - DOCKER_UID=${VXL_UID}
      - DOCKER_GIDS=${VXL_GIDS}
      - DOCKER_GROUP_NAMES=${VXL_GROUP_NAMES}
      - DOCKER_USERNAME=user

      #- DOCKER_HOME=${VXL_HOME}

      - DISPLAY
#     cap_add:
#       - SYS_PTRACE # Useful for gdb
    volumes:
      - type: ${VXL_SOURCE_DIR_TYPE}
        source: ${VXL_SOURCE_DIR}
        target: ${VXL_SOURCE_DIR_DOCKER}
        read_only: true
      - type: ${VXL_BUILD_DIR_TYPE}
        source: ${VXL_BUILD_DIR}
        target: ${VXL_BUILD_DIR_DOCKER}
      - type: ${VXL_INSTALL_DIR_TYPE}
        source: ${VXL_INSTALL_DIR}
        target: ${VXL_INSTALL_DIR_DOCKER}
      - type: volume
        source: venv
        target: /venv
  vxl2:
    <<: *vxl_anchor
volumes:
  venv:
  vxl-install:
  vxl-build:
