version: 2
jobs:
  build:
    working_directory: ~/terra
    shell: /bin/bash -eo pipefail
    docker:
      - image: vsiri/circleci:bash-compose-lfs
    steps:
      - checkout

      - run:
          name: Checkout submodules
          command: |
            git submodule sync
            git submodule update --init --recursive

      - run:
          name: Additional setup
          command: |
            touch local.env

      # - run:
      #     name: Checkout test data (git-lfs)
      #     command: |
      #       git lfs install
      #       git lfs pull

      - setup_remote_docker

      - run:
          name: Smuggle repo to remote docker
          command: tar zc --exclude .git . | docker run -i -v /root/terra:/terra -w /terra alpine:3.6 tar zx

      - run:
          name: Build dockers
          command: |
            source setup.env
            TERRA_PIPENV_DEV=1 just build terra

      - run:
          name: Running test code
          # no_output_timeout: 30m
          command: |
            source setup.env
            TERRA_LOCAL=0 just test terra ${CIRCLE_CI_TEST_FLAGS-}

      - run:
          name: Check pep8 compliance
          command: |
            source setup.env
            TERRA_LOCAL=0 just test pep8
