version: 2.1

# -----
# generic yaml anchors (reusable by multiple projects)
# -----
x-references:
  # container configuration & update
  container_config: &container_config
    working_directory: ~/repo
    shell: /bin/bash -eu
    docker:
      - image: vsiri/circleci:bash-compose-lfs

commands:
  submodule_checkout:
    description: Checks out submodules
    steps:
      - run:
          name: Checkout submodules
          command: |
            git submodule sync
            git submodule update --recursive --init

  common_setup:
    description: Setup terra environment
    steps:
      - checkout
      - submodule_checkout
      - setup_remote_docker
      - run:
          name: Additional setup
          command: echo 'TERRA_LOCAL=0' >  local.env

      # - run:
      #     name: Checkout test data (git-lfs)
      #     command: |
      #       git lfs install
      #       git lfs pull

      - run:
          name: Smuggle repo to remote docker
          command: |
            echo hi > redis_password.secret
            tar zc --exclude .git . | docker run -i -v /root/repo:/repo -w /repo alpine:3.6 tar zx


jobs:
  run_tests:
    <<: *container_config
    steps:
      - common_setup

      - run:
          name: Build dockers
          command: |
            source setup.env
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
            docker pull vsiri/ci_cache:terra || :
            docker pull vsiri/ci_cache:terra_redis || :
            docker pull vsiri/ci_cache:terra_pipenv || :
            docker build --target pipenv_cache --cache-from vsiri/ci_cache:terra_pipenv --file docker/terra.Dockerfile .
            just terra sync
            just terra pipenv sync --dev
            docker tag terra:terra_$(id -un) vsiri/ci_cache:terra
            docker tag terra:redis_$(id -un) vsiri/ci_cache:terra_redis
            docker tag terra:terra_pipenv_$(id -un) vsiri/ci_cache:terra_pipenv
            # if [ "${CIRCLE_PROJECT_USERNAME}" = "visionsystemsinc" ] && [ "${CIRCLE_BRANCH}" != "master" ]; then
              docker push vsiri/ci_cache:terra
              docker push vsiri/ci_cache:terra_redis
              docker push vsiri/ci_cache:terra_pipenv
            # fi

###       - run:
###           name: Running test code
###           # no_output_timeout: 30m
###           command: |
###             source setup.env
###             just terra test ${CIRCLE_CI_TEST_FLAGS-}

###       - run:
###           name: Check pep8 compliance
###           command: |
###             source setup.env
###             just terra test-pep8

  compile_docs:
    <<: *container_config
    steps:
      - common_setup

      - run:
          name: Generate docs
          command: |
            . setup.env
            SPHINXOPTS='-W' just sphinx build compile -n --all
      - run:
          name: Smuggle docs back from remote docker
          command: |
            docker run --rm -v /root/repo:/src -w /src alpine:3.8 tar c ./docs/_build/html | tar x

      - persist_to_workspace:
          root: docs/_build
          paths: html


  deploy_docs:
    <<: *container_config
    steps:
      - checkout
      - attach_workspace:
          at: /docs
      - run:
          name: Checkout gh-pages and update
          command: |
            git checkout gh-pages || git checkout --orphan gh-pages
            find . -maxdepth 1 -path ./.git -prune -o -name . -o  -exec rm -rf {} +
            mv /docs/html/* ./
            touch .nojekyll

            git add --all
            git config --global user.email "circleci@cirleci.com" > /dev/null 2>&1
            git config --global user.name "CircleCI" > /dev/null 2>&1
            git commit -m "Autobuild documentation [ci skip]"
            git remote set-url origin "https://${GH_NAME}:${GH_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git"
            git push origin gh-pages

# -----
# CircleCI workflows
# -----
workflows:
  terra:
    jobs:
      - run_tests
###       - compile_docs
###       - deploy_docs:
###           requires:
###             - compile_docs
###           filters:
###             branches:
###               only:
###                 - master
